DELETE FROM custom; 
INSERT INTO custom (category, value, available) VALUES ("flavor", "Chocolate", 1);
INSERT INTO custom (category, value, available) VALUES ("flavor", "Vanilla", 1); 
INSERT INTO custom (category, value, available) VALUES ("flavor", "Butter", 1); 
INSERT INTO custom (category, value, available) VALUES ("flavor", "Strawberry", 1); 
INSERT INTO custom (category, value, available) VALUES ("flavor", "Red Velvet", 1); 
INSERT INTO custom (category, value, available) VALUES ("flavor", "Carrot", 1); 
INSERT INTO custom (category, value, available) VALUES ("frosting", "Chocolate", 1); 
INSERT INTO custom (category, value, available) VALUES ("frosting", "Vanilla", 1); 
INSERT INTO custom (category, value, available) VALUES ("frosting", "Strawberry", 1); 
INSERT INTO custom (category, value, available) VALUES ("frosting", "Peanut Butter", 1); 
INSERT INTO custom (category, value, available) VALUES ("frosting", "Cream Cheese", 1); 
INSERT INTO custom (category, value, available) VALUES ("filling", "[None]", 1); 
INSERT INTO custom (category, value, available) VALUES ("filling", "Chocolate Pudding", 1); 
INSERT INTO custom (category, value, available) VALUES ("filling", "Fruit", 1); 
INSERT INTO custom (category, value, available) VALUES ("filling", "Marshmallow Cream", 1); 
DELETE FROM dessert_item; 
INSERT INTO dessert_item (name, image_file_name, description, price, available) VALUES ("Chocolate-Dipped Pretzels", "chocolate_dipped_pretzel_rods.jpg", "Pretzels dipped in chocolate and sprinkles (6)", 2.99, 1);
INSERT INTO dessert_item (name, image_file_name, description, price, available) VALUES ("Rice Krispie Treat", "White-Chocolate-Krispie-Treats-Image.JPG", "Traditional Rice Krispie Treat dipped in white chocolate", 0.99, 1); 
INSERT INTO dessert_item (name, image_file_name, description, price, available) VALUES ("Cake Balls", "cake_balls.jpg", "Assorted cake balls (6)", 2.99, 1); 
INSERT INTO dessert_item (name, image_file_name, description, price, available) VALUES ("Chocolate Chip Cookies", "chocolate_chip_cookies.jpg", "Traditional chocolate chip cookies, like mom used to make (6)", 5.99, 1); 
INSERT INTO dessert_item (name, image_file_name, description, price, available) VALUES ("Peanut Butter Cookies", "peanut_butter_cookies.jpg", "Peanut butter-flavored cookies (6)", 5.99, 1); 
INSERT INTO dessert_item (name, image_file_name, description, price, available) VALUES ("Sugar Cookies", "frosted_sugar_cookies.jpg", "Classic sugar cookies, with pink frosting and sprinkles (6)", 5.99, 1); 
INSERT INTO dessert_item (name, image_file_name, description, price, available) VALUES ("Snickerdoodles", "snickerdoodles.jpg", "Cookies baked with cinnamon and sugar (6)", 5.99, 1); 
INSERT INTO dessert_item (name, image_file_name, description, price, available) VALUES ("Chocolate Cupcakes", "chocolate_cupcakes.jpg", "Chocolate cupcakes with chocolate frosting (4)", 4.99, 1);
